before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
language: python
python:
  - "3.5"
install:
  - pip install pytest
  - pip install selenium
script: py.test -v 
